# Base image
FROM node:18-alpine

# Fix Turbo issue
# https://stackoverflow.com/questions/75174308/turbo-crashes-with-any-command-in-official-node-docker-image-alpine
RUN apk add --no-cache libc6-compat

WORKDIR /usr/src/app

COPY . .

RUN npm ci --omit=dev

EXPOSE 3001

RUN npm run build

CMD cd apps/api && npm run start:prod