on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install packages
        run: npm ci

      - name: Run tests
        run: npm test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install packages
        run: npm ci

      - name: Build packages
        run: npm run build

  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #   environment: production

  #   steps:
  #     - name: Install packages
  #       uses: actions/setup-node

  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         path: "packages/ui"
